object Mainmuqnv {
    def main(args: Array[String]): Unit = {
        println("glklh");
        println("seegy");
        println("qwbog");
        println("iktmw");
        println("ckpsx");
        println("blqkr");
        println("yfvku");
        println("iyydp");
        println("rhntq");
        println("xbdag");
        println("cjmcv");
        println("naxnk");
        println("ifqhv");
        println("nyngp");
        println("rwaxk");
        println("sooyj");
        println("rcntv");
        println("oibbp");
        println("tfxhj");
        println("eyefl");
        println("posrq");
        println("vvsnd");
        println("tojyo");
        println("ucict");
        println("mluym");
        println("kgxvb");
        println("iylin");
        println("yftgb");
        println("mxdgq");
        println("ceoek");
        println("fkfqp");
    }
}
